version: '3'
services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    command: redis-server
  element-core:
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - ENV=local
    command: nodemon --exec npm run dev