version: '3'
services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    command: redis-server
  element-core:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379